#!/bin/bash
# /etc/init.d/scphabtts

# INSTALL
# this script should be located in "/etc/init.d/"
# to Install service to be run at boot-time, run: 
# update-rc.d scphabtts defaults

### BEGIN INIT INFO
# Provides:   screen.sh
# Required-Start: $local_fs $remote_fs
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: Scphabtts-server 
# Description:    This runs scphabtts server continuously in screen. 
### END INIT INFO
DIR=/home/pi/scphabtts
DAEMON_NAME=scphabtts
DAEMON_USER=pi

case "$1" in

  start)
        echo "Starting screen.sh"
        su -l $DAEMON_USER -c "screen -fa -d -m python $DIR/main.py"
        ;;
  stop)
        echo "Stopping screen.sh"
        PID=`ps -ef | grep main.py | grep -v grep | awk '{print $2}'`
        kill -9 $PID 
        ;;

  restart|force-reload)
        echo "Restarting $screen"
        PID=`ps -ef | grep main.py | grep -v grep | awk '{print $2}'`
        kill -9 $PID 
        sleep 15
	su -l $DAEMON_USER -c "screen -fa -d -m python $DIR/main.py"
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac
exit 0
